# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TaskTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskTracker
  pod 'RealmSwift', '=10.0.0-beta.2'

end
